version: '3.9'

services:
  app:
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jumarket-application
      MYSQL_USER: erick
      MYSQL_PASSWORD: tqi
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: