spring:
  datasource:
    url: jdbc:mysql://mysql_host:3306/jumarket-application
    username: erick
    password: tqi
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html