spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jumarket
    username: erick
    password: tqi123@
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update