spring:
  profiles:
    active: h2

---

spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/jumarket
    username: erick
    password: tqi@
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

---

spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: jax
    password:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
